# Experiment Config for each experiment
output_dir: /output
logging_dir: runs
logging_steps: 10
seed: 1115
train_file: csv/vggsound/train_above_5s.csv
validation_file: csv/vggsound/valid_above_5s.csv
demo_file: csv/vggsound/demo.csv
demo_metadata: csv/vggsound/demo_meta.csv
dac_base_path: /data/vggsound/dac
clip_base_path: /data/vggsound/clip
model_cfg: cfg/config.json
overwrite_output_dir: False

# Basic Config
num_train_epochs: 50
max_train_steps: null
seconds_to_use: 5
gradient_accumulation_steps: 1
per_device_train_batch_size: 64
per_device_eval_batch_size: 64
split_batches: true
checkpointing_steps: epoch  # 'epoch' to save for each epoch, or number of steps
resume_from_checkpoint: null

# Training Hyperparameters
# "lr_schedulre_type" should be one of "linear", "cosine", "cosine_with_restarts", "polynomial", 
# "constant", "constant_with_warmpup", "inverse_sqrt", "reduce_lr_on_plateau", "two_stage_inverse_sqrt"
lr_scheduler_type: constant_with_warmup
learning_rate: 1e-4  # peak lr
num_warmup_steps: 4000
weight_decay: 0.01
max_grad_norm: 1.0

# Others
with_tracking: true
report_to: tensorboard
ignore_pad_token_for_loss: true 
preprocessing_num_workers: 32
overwrite_cache: false